Helper method for the parsing of a sdjwt string to retrieve claims
eu-digital-identity-wallet/eudi-lib-jvm-sdjwt-kt pull request #201
Opened 2024-06-25 10:55 UTC by goncalo-frade-iohk

As a developer I may want to process an SDJWT without verifying.

Having a helper function that would initialise a holder SdJwt, would simplify this process.
This way I could initialise a SdJWT without the need of having a suspended function.

This would be very useful when as a holder you want to process the claims of a saved SDJwt without the need of verifying it again.
I understand there is JwtSignatureVerifier.Companion.NoSignatureValidation but it still requires to be suspended.

2024-06-26 08:36 UTC, babisRoutis requested changes
Hi @goncalo-frade-iohk 

Instead of changing the `SdJwtVerifier` please consider to introduce a method that will look like the following 

```kotlin
val sdJwt = SdJwt.unverifiedIssuanceFrom(unverifiedSdJwt).getOrThrow()
```
If you agree, then bellow are some concrete instructions:


In file `SdJwtVerifier.kt`
 - Mark the method `fun parseIssuance()` as internal
 - Add a new top-level method 
 
 ```kotlin
 internal fun verifyIssuance(
    unverifiedJwt: Jwt,
    unverifiedDisclosures: List<String>,
    jwtClaimsExtractor: (Jwt)->Claims,
): Result<SdJwt.Issuance<JwtAndClaims>> = runCatching {
    val jwtClaims = jwtClaimsExtractor(unverifiedJwt)
    val hashAlgorithm = hashingAlgorithmClaim(jwtClaims)
    val disclosures = uniqueDisclosures(unverifiedDisclosures)
    val digests = collectDigests(jwtClaims, disclosures)

    // Check Disclosures
    verifyDisclosures(hashAlgorithm, disclosures, digests)

    // Assemble it
    SdJwt.Issuance(unverifiedJwt to jwtClaims, disclosures)
}
 ```
- Refactor line 308 to call the above method

In file `Types.kt`
- Add an empty companion object to SdJwt interface 
```kotlin
sealed interface SdJwt<out JWT> {
...
  companion object 
}
``` 

Finally, in file `NimbusIntegration.kt` 
- Add a new top-level method 
```kotlin
fun SdJwt.Companion.unverifiedIssuanceFrom(unverifiedSdJwt: String):Result<SdJwt.Issuance<JwtAndClaims>> = runCatching{
    val (unverifiedJwt, unverifiedDisclosures) = parseIssuance(unverifiedSdJwt)
    verifyIssuance(unverifiedJwt, unverifiedDisclosures){
        NimbusSignedJWT.parse(unverifiedJwt).jwtClaimsSet.asClaims()
    }.getOrThrow()
}
```

2024-06-26 09:35 UTC, babisRoutis commented
Closes #201

2024-07-05 15:41 UTC, goncalo-frade-iohk commented
Hey @babisRoutis sorry I had some priority items to go through this week. Next week I will be able to finalize this changes.

2024-07-05 16:30 UTC, babisRoutis commented
@goncalo-frade-iohk 
No worries. 
Please make sure to rebase `main` on your branch when you ready for review.

2024-07-15 08:07 UTC, VHerasymov commented
@goncalo-frade-iohk @babisRoutis Hello guys, we're looking for an update with this PR since need this feature as well. If you need, we can offer a help

2024-07-15 09:52 UTC, babisRoutis commented
@goncalo-frade-iohk , @VHerasymov  I am closing this.
Please follow https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-sdjwt-kt/pull/212

2024-07-15 09:52 UTC, closed without merging

2024-07-15 10:17 UTC, babisRoutis commented
@goncalo-frade-iohk , @VHerasymov PR #212 has been merged and included in v0.5.1
Shortly, you would be able to get the new version from maven central.

2024-07-18 14:13 UTC, goncalo-frade-iohk commented
@babisRoutis @VHerasymov was coming now to finally finalise this, and noticed it was merged. Sorry for the delay had a few crazy 2 weeks.

And thank you @babisRoutis for finalising it 🚀